version: '3'

services:
    mongodb:
        image: mongo:latest
        volumes: 
            - db:/data/db
        networks: 
            - myapp
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
    nodejs:
        image: "vlhoang/nodejs-mongodb:latest"
        ports: 
            - 8000:3000
        environment: 
            - MONGODB_URI=mongodb://mongodb:27017/demo
            - PORT=3000
        networks: 
            - myapp
        deploy:
            mode: replicated
            replicas: 3
            resources:
                limits:
                    cpus: "0.50"
                    memory: 58M
                reservations:
                    cpus: "0.25"
                    memory: 20M

networks: 
    myapp:

volumes: 
    db:
    